// 7. Ask user’s age and check if eligible to vote
// If age >= 18 → “Eligible”, else → “Not eligible”

// 8. Print multiplication table of 5
// Use loop to print 5 × 1 to 5 × 10.

// 9. Count how many numbers between 1 and 15 are greater than 8
// Loop and count conditionally.

// 10. Ask user for password and print access status
// Hardcoded correct password. Compare with user input.

// Level 2 – Slightly Tougher but Logical
// 11. Allow only 3 attempts to enter correct password
// If user gets it right early, stop. If not → “Account locked”

let prompt = require("prompt-sync")();
// 1 Answer
// let password = 12365;
// let attempts = 3;

// while(attempts > 0){
//   const userInput = Number(prompt("Enter Your Password :-"));
//   if(password === userInput){
//     console.log("your password maced login ");
//     break;
//   }
//   else {
//     attempts --;
//     if(attempts > 0) {
//       console.log(`Wrong password! ${attempts} attempt(s) remaining.`)
//     }
//   }
// }

// if(attempts === 0) console.log("password not mached Your account locked :-");


// 12. Ask user for words until they type “stop”. Count how many times they typed “yes”
// Loop until "stop" is typed. Count "yes".

// let count = 0;
// while(true) {
//   let word = prompt("Enter Your worrd :-");
//   if(word == "stop") {
//     console.log(" stop");
//     break;
//   }
//   if(word == "yes") {
//     count ++;
//   }
// }







