// 7. Ask user’s age and check if eligible to vote
// If age >= 18 → “Eligible”, else → “Not eligible”

// 8. Print multiplication table of 5
// Use loop to print 5 × 1 to 5 × 10.

// 9. Count how many numbers between 1 and 15 are greater than 8
// Loop and count conditionally.

// 10. Ask user for password and print access status
// Hardcoded correct password. Compare with user input.

// Level 2 – Slightly Tougher but Logical
// 11. Allow only 3 attempts to enter correct password
// If user gets it right early, stop. If not → “Account locked”


// 1 Answer
let prompt = require("prompt-sync")();

// let age =  Number(prompt("Enter Your Age :-"));
// if(age >= 18 ) console.log("Elogibale for Vote :");
// else console.log("not Elogibale");

// 2 Answer
// let num = Number(prompt("Enter Your Number  for Printing table:-"));

// for(let i = 1; i<=10; i++){
//   let multi = num * i;
//   console.log(num + " * " + i + " = " + multi );
// }


// let count = 0;
// for(let i = 1; i<=15; i++){
  
//   if(i > 7) 
//   count ++;
  
// }

// console.log(count);

// let password = Number(prompt("Enter your password"));
// let hardcodepassword = 123456;
// if(password === hardcodepassword) console.log("Your password was correct ");
// else console.log("password not correct ");